apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-openstack-1-0-2
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-openstack
      version: 1.0.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
