apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: openstack-standalone-cp-1-0-4
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: openstack-standalone-cp
      version: 1.0.4
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
