apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Release
metadata:
  name: kcm-1-0-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  version: 1.0.0
  kcm:
    template: kcm-1-0-0
  capi:
    template: cluster-api-1-0-2
  providers:
    - name: cluster-api-provider-k0sproject-k0smotron
      template: cluster-api-provider-k0sproject-k0smotron-1-0-2
    - name: cluster-api-provider-azure
      template: cluster-api-provider-azure-1-0-2
    - name: cluster-api-provider-vsphere
      template: cluster-api-provider-vsphere-1-0-1
    - name: cluster-api-provider-aws
      template: cluster-api-provider-aws-1-0-2
    - name: cluster-api-provider-openstack
      template: cluster-api-provider-openstack-1-0-2
    - name: cluster-api-provider-docker
      template: cluster-api-provider-docker-1-0-1
    - name: cluster-api-provider-gcp
      template: cluster-api-provider-gcp-1-0-2
    - name: cluster-api-provider-ipam
      template: cluster-api-provider-ipam-1-0-2
    - name: cluster-api-provider-infoblox
      template: cluster-api-provider-infoblox-1-0-1
    - name: projectsveltos
      template: projectsveltos-0-54-0
