{{- $global := .Values.global | default dict }}
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version | replace "+" "-" }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $global.registry }}
  image: {{ $global.registry }}/k0s
  etcd:
    image: "{{ $global.registry }}/etcd:v3.5.13"
  {{- if $global.registryCertSecret }}
  mounts:
    - path: /usr/local/share/ca-certificates/registry
      secret:
        defaultMode: 420
        items:
          - key: ca.crt
            path: ca.crt
        secretName: {{ $global.registryCertSecret }}
  {{- end }}
  {{- end }}
  controllerPlaneFlags:
  - "--enable-cloud-provider=true"
  - "--debug=true"
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      {{- with .Values.k0s.api.extraArgs }}
      api:
        extraArgs:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      network:
        provider: calico
        calico:
          mode: vxlan
      {{- if $global.registry }}
      images:
        metricsserver:
          image: "{{ $global.registry }}/k0sproject/metrics-server"
        kubeproxy:
          image: "{{ $global.registry }}/k0sproject/kube-proxy"
        coredns:
          image: "{{ $global.registry }}/k0sproject/coredns"
        pause:
          image: "{{ $global.registry }}/k0sproject/pause"
        calico:
          cni:
            image: "{{ $global.registry }}/k0sproject/calico-cni"
          node:
            image: "{{ $global.registry }}/k0sproject/calico-node"
          kubecontrollers:
            image: "{{ $global.registry }}/k0sproject/calico-kube-controllers"
      {{- end }}
      extensions:
        helm:
          repositories:
          {{- if not $global.registry }}
            - name: vsphere-cpi
              url: https://kubernetes.github.io/cloud-provider-vsphere
            - name: mirantis
              url: https://charts.mirantis.com
          {{- else }}
            - name: global-registry
              url: oci://{{ $global.registry }}
              {{- if $global.registryCertSecret }}
              caFile: /usr/local/share/ca-certificates/registry/ca.crt
              {{- end }}
          {{- end }}
          charts:
          - name: vsphere-cpi
            {{- if $global.registry }}
            chartname: oci://{{ $global.registry }}/charts/vsphere-cpi
            {{- else }}
            chartname: vsphere-cpi/vsphere-cpi
            {{- end }}
            version: 1.31.0
            order: 1
            namespace: kube-system
            values: |
              config:
                enabled: false
              daemonset:
                affinity: null
                {{- if $global.registry }}
                image: {{ $global.registry }}/cloud-pv-vsphere/cloud-provider-vsphere
                {{- end }}
                tolerations:
                  - effect: NoSchedule
                    key: node.cloudprovider.kubernetes.io/uninitialized
                    value: "true"
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/master
                    operator: Exists
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/control-plane
                    operator: Exists
                  - effect: NoSchedule
                    key: node.kubernetes.io/not-ready
                    operator: Exists
                  - key: CriticalAddonsOnly
                    effect: NoExecute
                    operator: Exists
          - name: vsphere-csi-driver
            {{- if $global.registry }}
            chartname: oci://{{ $global.registry }}/charts/vsphere-csi-driver
            {{- else }}
            chartname: mirantis/vsphere-csi-driver
            {{- end }}
            version: 0.0.3
            order: 2
            namespace: kube-system
            values: |
              vcenterConfig:
                enabled: false
              controller:
                nodeAffinity: null
              node:
                kubeletPath: /var/lib/k0s/kubelet
              defaultStorageClass:
                enabled: true
              images:
                driver:
                  {{- if $global.registry }}
                  repo: {{ $global.registry }}/csi-vsphere/driver
                  {{- end }}
                  tag: v3.1.2
                syncer:
                  {{- if $global.registry }}
                  repo: {{ $global.registry }}/csi-vsphere/syncer
                  {{- end }}
                  tag: v3.1.2
                {{- if $global.registry }}
                nodeDriverRegistrar:
                  repo: {{ $global.registry }}/sig-storage/csi-node-driver-registrar
                csiAttacher:
                  repo: {{ $global.registry }}/sig-storage/csi-attacher
                csiResizer:
                  repo: {{ $global.registry }}/sig-storage/csi-resizer
                csiProvisioner:
                  repo: {{ $global.registry }}/sig-storage/csi-provisioner
                csiSnapshotter:
                  repo: {{ $global.registry }}/sig-storage/csi-snapshotter
                livenessProbe:
                  repo: {{ $global.registry }}/sig-storage/livenessprobe
                {{- end }}
