apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: gcp-${CLUSTER_NAME_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: gcp-standalone-cp-1-0-4
  credential: gcp-credential
  config:
    clusterLabels: {}
    clusterAnnotations: {}
    project: k0rdent-dev
    region: us-east4
    network:
      name: default
    controlPlane:
      instanceType: n1-standard-2
      image: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20250213
      publicIP: true
    controlPlaneNumber: 1
    worker:
      instanceType: n1-standard-2
      image: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20250213
      publicIP: true
    workersNumber: 1
