apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: vsphere-${CLUSTER_NAME_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: vsphere-standalone-cp-1-0-3
  credential: vsphere-cluster-identity-cred
  config:
    clusterLabels: {}
    clusterAnnotations: {}
    controlPlaneNumber: 1
    workersNumber: 1
    vsphere:
      server: ${VSPHERE_SERVER}
      thumbprint: ${VSPHERE_THUMBPRINT}
      datacenter: ${VSPHERE_DATACENTER}
      datastore: ${VSPHERE_DATASTORE}
      resourcePool: ${VSPHERE_RESOURCEPOOL}
      folder: ${VSPHERE_FOLDER}
      username: ${VSPHERE_USER}
      password: ${VSPHERE_PASSWORD}
    controlPlaneEndpointIP: ${VSPHERE_CONTROL_PLANE_ENDPOINT}
    controlPlane:
      ssh:
        user: ubuntu
        publicKey: ${VSPHERE_SSH_KEY}
      rootVolumeSize: 50
      cpus: 4
      memory: 4096
      vmTemplate: ${VSPHERE_VM_TEMPLATE}
      network: ${VSPHERE_NETWORK}
    worker:
      ssh:
        user: ubuntu
        publicKey: ${VSPHERE_SSH_KEY}
      rootVolumeSize: 50
      cpus: 4
      memory: 4096
      vmTemplate: ${VSPHERE_VM_TEMPLATE}
      network: ${VSPHERE_NETWORK}
