apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: mcs1
spec:
  clusterSelector:
    matchLabels:
      owner: dev-team
  serviceSpec:
    provider:
      name: ksm-projectsveltos
      config:
        continueOnError: true
        stopOnConflict: false
        priority: 200
    services:
      - template: ingress-nginx-4-13-0
        name: nginx
        namespace: nginx
        values: |
          ingress-nginx:
            global:
              image:
                registry: this.does.not.exist.com
        helmOptions:
          timeout: 1s