{{- $global := .Values.global | default dict }}
{{- $version := .Chart.AppVersion }}
{{- $kubeRbacProxyVersion := "v0.13.1" }}
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: k0sproject-k0smotron
spec:
  version: {{ $version }}
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
  {{- if $global.registry }}
  fetchConfig:
    oci: {{ $global.registry }}/capi/cluster-api-provider-k0sproject-k0smotron-components:{{ $version }}
  deployment:
    containers:
      - name: manager
        imageUrl: {{ $global.registry }}/capi/k0smotron:{{ $version }}
      - name: kube-rbac-proxy
        imageUrl: {{ $global.registry }}/kubebuilder/kube-rbac-proxy:{{ $kubeRbacProxyVersion }}
  {{- end }}
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: BootstrapProvider
metadata:
  name: k0sproject-k0smotron
spec:
  version: {{ $version }}
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
  {{- if $global.registry }}
  fetchConfig:
    oci: {{ $global.registry }}/capi/cluster-api-provider-k0sproject-k0smotron-components:{{ $version }}
  deployment:
    containers:
      - name: manager
        imageUrl: {{ $global.registry }}/capi/k0smotron:{{ $version }}
      - name: kube-rbac-proxy
        imageUrl: {{ $global.registry }}/kubebuilder/kube-rbac-proxy:{{ $kubeRbacProxyVersion }}
  {{- end }}
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: k0sproject-k0smotron
spec:
  version: {{ $version }}
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
  {{- if $global.registry }}
  fetchConfig:
    oci: {{ $global.registry }}/capi/cluster-api-provider-k0sproject-k0smotron-components:{{ $version }}
  deployment:
    containers:
      - name: manager
        imageUrl: {{ $global.registry }}/capi/k0smotron:{{ $version }}
      - name: kube-rbac-proxy
        imageUrl: {{ $global.registry }}/kubebuilder/kube-rbac-proxy:{{ $kubeRbacProxyVersion }}
  {{- end }}
